version: '3.4'

services: 
    hello-polkadot:
        #image: ubuntu:20.04
        build:
            context: dockerfiles
            dockerfile: Dockerfile 
        container_name: hello-polkadot 
        port: 
            - "8001:8000"
        command: "bash"

