version: '3.4'

services: 
    hello-polkadot:
        #image: ubuntu:20.04
        build:
            context: dockerfiles
            dockerfile: Dockerfile 
        container_name: hello-polkadot 
        ports: 
            - "8000:8000"
            - "9944:9944"
        volumes: 
            - ./start_services.sh:/start_services.sh
            - ./bucket:/bucket
        #command: "bash /start_services.sh"
        command: "bash /start_services.sh"

